version: '3.8'
services:
  service-db:
    image: postgres:15-alpine3.19
    environment:
      POSTGRES_DB: "summer"
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
#      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: